
admin:
    username: u1
    password: adminPassword1
    birthday: "19/09/1996"
    country: Israel
    city: Ashdod
    address: Elul
    name: David Volodarsky

paymentService:
  url: https://damp-lynna-wsep-1984852e.koyeb.app/

supplyService:
  url: https://damp-lynna-wsep-1984852e.koyeb.app/
